# Generated by Django 4.2.15 on 2024-09-08 03:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
