# Generated by Django 4.2.15 on 2024-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_campaign_description_campaign_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
