# Generated by Django 4.2.15 on 2024-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
