# Generated by Django 4.2.15 on 2024-09-13 12:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_product_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
